[workspace]
members = [
    "crates/ruri",
    "crates/ruri-interceptor",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = [
    "Seuriin (SSL-ACTX) <seuriin@gmail.com>",
    "Iris-Seravelle <iris.seravelle@gmail.com>",
]
license = "Apache-2.0"
repository = "https://github.com/SSL-ACTX/ruri"

[workspace.dependencies]
ruri-interceptor = { path = "crates/ruri-interceptor" }
libc = "0.2"
rsa = { version = "0.9", default-features = false, features = ["std", "pem"] }
base64 = "0.22"
rand = "0.8"
num-bigint = { version = "0.4", default-features = false }
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
rcgen = "0.13"
ring = "0.17"
curve25519-dalek = { version = "4", features = ["rand_core"] }

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
incremental = false

[profile.dev]
opt-level = 1
debug = 1
strip = true
panic = "unwind"
lto = false
codegen-units = 256
incremental = true
